### ISSUE TITLE
Similar project name

### ISSUE THREAD

**Issue by vsergeev** [minrk/umsgpack#1]
This project is named similarly to https://github.com/vsergeev/u-msgpack-python, though in that case the u connotes "micro". It also shares the same import line `import umsgpack`. I'm not asking you to change the name, I'm just leaving an issue here in case others are confused by this in the future (as I was when installing it via pip :wink:).

**Comment by minrk** [comment]
Sorry about that, I didn't know about yours! I can rename mine (e.g. to `msgpacku`) if you'd like, I don't think there are many (if any) users out there of this guy at this point. Also, it seems that your implementation also solves my primary annoyance at the default implementation by default, so maybe I didn't need to make this in the first place.

**Comment by vsergeev** [comment]
`msgpacku`, `msgpack-unicode`, `msgpack-unicode-python`, `unicode-msgpack-python`, etc. all sound fine to me, if you are comfortable with changing it. I think it will make the two PyPI package names less ambiguous (currently there is `u-msgpack-python` and `umsgpack`, and it's not obvious they're different implementations).

`u-msgpack-python` does address unicode encoding/decoding consistently, but it won't be as performant as your wrapper, since `u-msgpack-python` is a pure Python implementation. It's main purpose is provide a portable, drop-in implementation that doesn't requiring any compilation (which is a major pain point for Python when cross-compiling for another architecture, IMO).

**Comment by minrk** [comment]
Published msgpacku, and updated the description of umsgpack to point to u-msgpack-python and msgpacku.
